[package]
name = "vector-lite"
version = "0.1.0"
edition = "2024"
description = "The SQLite of Vector Database in Rust."
authors = ["Xiangpeng Hao <haoxiangpeng123@gmail.com>"]

[dependencies]
rand = "0.9.0"
flexbuffers = "25.2.10"
serde = { version = "1.0.215", features = ["derive"] }

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "ann_benchmark"
harness = false


[profile.bench]
lto = true
